create table customer (
  id bigint generated by default as identity primary key,
  first_name varchar(255),
  last_name varchar(255)
);

create table "order" (
  id bigint generated by default as identity primary key,
  ordered_by bigint references customer(id),
  ordered_on timestamp
);

create table product (
  id bigint generated by default as identity primary key,
  name varchar(255),
  price decimal(8,2)
);

create table order_product (
  order_id bigint references "order"(id) not null,
  product_id bigint references product(id) not null
);